      - name: Run script
        run: node scripts/update.js

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: page
          path: |
            page.html
            screenshot.png
